# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    app.pgManager.limit: '10'

services:
    app.pgManager:
        class: AppBundle\Services\PaginateManager
        arguments: ['%app.pgManager.limit%']

    # Post Helper Service
    app.PostHelper:
        class: AppBundle\Services\Post\PostHelper
        arguments: [ '@doctrine.orm.entity_manager', '@app.pgManager', '%app.pgManager.limit%' ]

    # Category Helper Service
    app.CategoryHelper:
        class: AppBundle\Services\Category\CategoryHelper
        arguments: ['@doctrine.orm.entity_manager', '@app.pgManager', '%app.pgManager.limit%']

